spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finance_db
    username: your_user
    password: your_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: mysecretkey1234567890
  expirationMs: 86400000