spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finance_db
    username: your_user
    password: your_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always